root = "."
tmp_dir = "tmp"

[build]

cmd = "go build -o bin/app main.go"
bin = "./bin/app"
full_bin = "APP_ENV=dev APP_USER=air ./bin/app"
args_bin = ["serve", '--http="localhost:8090"']
include_ext = ["go", "templ", "html","css"]
exclude_dir = ["assets","bin"]
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
follow_symlink = true
log = "air.log"
poll = false
poll_interval = 500
delay = 0
stop_on_error = true
send_interrupt = false
kill_delay = 500

rerun = true
rerun_delay = 500

[log]
time = false
main_only = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true