// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Product struct {
	ID          uuid.UUID
	Name        string
	Price       string
	ImageUrl    string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	Description string
}

type User struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Password  string
	Verified  bool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
